version: '3.8'

services:
  db_shared:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe000!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: ChangeMe000!
    volumes:
      - db_data:/var/lib/mysql

  wordpress1:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_shared:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ChangeMe000!
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db_shared
    ports:
      - "80:80"

  wordpress2:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_shared:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ChangeMe000!
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db_shared
    ports:
      - "80:80"

  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: mail.lung.se
    restart: always
    env_file: vars.env
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./config/:/tmp/docker-mailserver/
    environment:
      ENABLE_SPAMASSASSIN: 1
      ENABLE_CLAMAV: 1
      ENABLE_FAIL2BAN: 1
      ENABLE_POSTGREY: 0

  webmail:
    image: roundcube/roundcubemail:
    restart: always
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: imaps://mail.mail.lung.se
      ROUNDCUBEMAIL_SMTP_SERVER: tls://mail.mail.lung.se
    ports:
      - "80:80"
    depends_on:
      - mailserver

  postfixadmin:
    image: hardware/postfixadmin
    restart: always
    environment:
      - POSTFIXADMIN_DB_TYPE=mysqli
      - POSTFIXADMIN_DB_USER=admin
      - POSTFIXADMIN_DB_PASS=ChangeMe000!
      - POSTFIXADMIN_DB_HOST=db_shared
      - POSTFIXADMIN_DB_NAME=wordpress
      - POSTFIXADMIN_ADMIN_USER=admin
      - POSTFIXADMIN_ADMIN_PASS=ChangeMe000!
    depends_on:
      - db_shared
    ports:
      - ":80"

volumes:
  db_data:
  maildata:
  mailstate:
