version: '3.9'

services:
  db_shared:
    image: mysql:5.7
    container_name: db_shared
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: ChangeMe000!
      MYSQL_ROOT_PASSWORD: ChangeMe000!
    volumes:
      - db_data_shared:/var/lib/mysql
    networks:
      - wpnet

  wordpress_lung.se:
    image: wordpress:latest
    container_name: wordpress_lung.se
    environment:
      WORDPRESS_DB_HOST: db_shared
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ChangeMe000!
      WORDPRESS_DB_NAME: wordpress_lung.se
    volumes:
      - ./wordpress_lung.se:/var/www/html
    networks:
      - wpnet

  wordpress_exsol.es:
    image: wordpress:latest
    container_name: wordpress_exsol.es
    environment:
      WORDPRESS_DB_HOST: db_shared
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ChangeMe000!
      WORDPRESS_DB_NAME: wordpress_exsol.es
    volumes:
      - ./wordpress_exsol.es:/var/www/html
    networks:
      - wpnet

  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: mail.lung.se
    container_name: mailserver
    env_file: vars.env
    ports:
      - "2525:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "465:465"
      - "110:110"
      - "995:995"
      - "4190:4190"
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./config:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: unless-stopped
    networks:
      - mailnet

  webmail:
    image: roundcube/roundcubemail:latest
    container_name: webmail
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: mail.lung.se
      ROUNDCUBEMAIL_SMTP_SERVER: tls://mail.lung.se
      ROUNDCUBEMAIL_SMTP_PORT: 587
      ROUNDCUBEMAIL_DEFAULT_PORT: 143
    volumes:
      - ./webmail:/var/www/html
    ports:
      - "8080:80"
    networks:
      - mailnet

networks:
  wpnet:
  mailnet:
volumes:
  db_data_shared:
